---
- name: Rust | Install packages
  block:
    - name: Check if rustup is installed
      ansible.builtin.command: "command -v rustup"
      register: rustup_check
      ignore_errors: true

    - name: Install rustup if not exist
      ansible.builtin.shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      when: rustup_check.rc != 0

    - name: Update rustup if exists
      ansible.builtin.shell: "rustup update"
      when: rustup_check.rc == 0
