---
- name: "SSH | Copy private key"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/id_ed25519"
    dest: "{{ ansible_user_dir }}/.ssh/"
    mode: "0600"

- name: "SSH | Copy public key"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/id_ed25519.pub"
    dest: "{{ ansible_user_dir }}/.ssh/"
    mode: "0644"

- name: "SSH | Copy config"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_user_dir }}/.ssh/"
    mode: "0644"

- name: "SSH | Set .ssh permission"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0700"
