---
- name: "Neovim | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true

- name: Rust | Install packages
  block:
    - name: Check if rustup is installed
      ansible.builtin.command: "command -v rustup"
      register: rustup_check
      ignore_errors: true

    - name: Install rustup if not exist
      ansible.builtin.shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      when: rustup_check.rc != 0

    - name: Update rustup if exists
      ansible.builtin.shell: "rustup update"
      when: rustup_check.rc == 0

- name: "Install Bob-nvim version manager"
  community.general.cargo:
    name: bob-nvim

- name: "Install Neovim with bob"
  ansible.builtin.command: bob use latest

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_dir }}/.config/nvim/"
    state: link
    force: true
# - name: "Neovim | Copy init.lua"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
#     src: "init.lua"
#     mode: "0644"
#
# - name: "Neovim | Copy .luarc.json"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/.luarc.json"
#     src: ".luarc.json"
#     mode: "0644"
# - name: "Neovim | Copy modules"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/lua"
#     src: "lua/"
#     mode: "0644"
